name: perl
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        perl-version: ['5.10', '5.14', '5.28']
        include:
          - perl-version: '5.32'
            os: ubuntu-latest
            more-test: true
            coverage: true
    container: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - run: cpanm -n --installdeps .
      - run: perl -V
      - name: Run extended tests
        if: ${{ matrix.more-test }}
        run: |
          cpanm -n --installdeps --with-develop --with-recommends .
      - name: Run tests
        if: ${{ !matrix.coverage }}
        run: prove -l -j4 t
      - name: Run tests (with coverage)
        if: ${{ matrix.coverage }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cpanm -n Devel::Cover::Report::Coveralls
          HARNESS_OPTIONS='j4' cover -test -report Coveralls
  non-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
          distribution: strawberry # ignored non-windows
      - uses: perl-actions/install-with-cpanm@v1
        with:
          args: -n --installdeps .
      - run: perl -V
      - name: Run tests
        run: prove -l -j4 t
